### 17 load iris & check keys

In [1]:
from sklearn.datasets import load_iris

iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [2]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
iris['data'][:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

### 18 check col names and category names

In [4]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
import pandas as pd
pd.DataFrame(data=iris['data'], columns=iris['feature_names'])

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [7]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

### 19 data & target

In [8]:
data = iris['data']
type(data)

numpy.ndarray

In [9]:
data.shape

(150, 4)

In [10]:
target = iris['target']
type(target)

numpy.ndarray

In [11]:
target.shape

(150,)

In [12]:
pd.Series(target).unique()

array([0, 1, 2])

### 20 training data & testing data

In [13]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(data, target, test_size=0.3) # return 4 dataset

In [14]:
print(data_train.shape) # 105 (70%) line predictor variables
print(target_train.shape) # 105 line response variable

(105, 4)
(105,)


In [15]:
print(data_test.shape) # 45 (rest 30%) line predictor variables
print(target_test.shape) # 45 line response variable

(45, 4)
(45,)


### 21 logistic regression

In [16]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(data_train, target_train)

LogisticRegression(max_iter=1000)

In [17]:
model.score(data_train, target_train)

0.9809523809523809

In [18]:
model.score(data_test, target_test)

0.9333333333333333

### 22 prediction

In [20]:
target_pred = model.predict(data_test)
target_pred.shape # same as target_test

(45,)

### 23 confusion matrix

In [21]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred) # diagonal are count of correctly predicted

array([[19,  0,  0],
       [ 0, 10,  1],
       [ 0,  2, 13]])

### 24 classification report

In [22]:
from sklearn.metrics import classification_report
print(classification_report(target_test, target_pred, target_names=iris['target_names']))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       0.83      0.91      0.87        11
   virginica       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.92      0.93      0.92        45
weighted avg       0.94      0.93      0.93        45

