### 34 linear regression

In [2]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'years':[1,2,3,4,5,6],'salary':[4000,4250,4500,4750,5000,5250]})
df

years  salary
0      1    4000
1      2    4250
2      3    4500
3      4    4750
4      5    5000
5      6    5250

In [3]:
m = len(df)
X1 = df['years'].values
X1

array([1, 2, 3, 4, 5, 6])

In [4]:
X = np.append(np.ones((m,1)),X1.reshape(m,1),axis=1)
X

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

In [5]:
y = df['salary']
y

0    4000
1    4250
2    4500
3    4750
4    5000
5    5250
Name: salary, dtype: int64

In [6]:
np.dot(X.T, y)

array([ 27750., 101500.])

In [7]:
coefs = np.dot(np.linalg.inv(np.dot(X.T,X)),np.dot(X.T, y)) # (X^TX)^(-1)X^Ty
coefs

array([3750.,  250.])

In [8]:
f'y = {coefs[0]} + {coefs[1]}*x'

'y = 3749.9999999999964 + 250.0*x'

### 35 sklearn linear regression

In [9]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(df[['years']],df[['salary']])
model.intercept_

array([3750.])

In [10]:
model.coef_

array([[250.]])

In [11]:
f'y = {model.intercept_[0]} + {model.coef_[0][0]}*x'

'y = 3750.0 + 250.0*x'

### 36 read csv and conduct linear regression

In [12]:
data = pd.read_csv('iris.csv')
data.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [16]:
model = LinearRegression()
model.fit(data[['sepal_length']], data[['sepal_width']])

LinearRegression()

In [17]:
model.score(data[['sepal_length']], data[['sepal_width']])

0.011961632834767588