### 39 csv value scaler

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [9]:
df = pd.read_csv('iris.csv')
df.drop('species', axis=1, inplace=True)
df.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [10]:
sc = StandardScaler()
sc.fit(df)

StandardScaler()

In [13]:
df_scaled = sc.transform(df)
df_scaled[:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

### 40 fit on train, transform on train and test

In [15]:
train = df[:100]
test = df[:50]
train.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [16]:
test.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [17]:
sc = StandardScaler()
sc.fit(train)

StandardScaler()

In [19]:
df_train = sc.transform(train)
df_test = sc.transform(test)
df_train[:5]

array([[-0.5810659 ,  0.85713543, -1.01435952, -1.03824799],
       [-0.89430898, -0.19845007, -1.01435952, -1.03824799],
       [-1.20755205,  0.22378413, -1.08374115, -1.03824799],
       [-1.36417359,  0.01266703, -0.94497788, -1.03824799],
       [-0.73768744,  1.06825253, -1.01435952, -1.03824799]])

In [20]:
df_test[:5]

array([[-0.5810659 ,  0.85713543, -1.01435952, -1.03824799],
       [-0.89430898, -0.19845007, -1.01435952, -1.03824799],
       [-1.20755205,  0.22378413, -1.08374115, -1.03824799],
       [-1.36417359,  0.01266703, -0.94497788, -1.03824799],
       [-0.73768744,  1.06825253, -1.01435952, -1.03824799]])

In [21]:
sc.mean_

array([5.471, 3.094, 2.862, 0.785])

In [22]:
sc.var_

array([0.407659, 0.224364, 2.077356, 0.317475])