In [1]:
import torch

In [2]:
torch.__version__

'1.13.0'

### create tensor

In [3]:
t1 = torch.tensor([1,2,3])
t1

tensor([1, 2, 3])

In [5]:
import numpy as np
array1 = np.arange(12).reshape(3,4)
torch.tensor(array1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
torch.rand([3,4]) # 0-1

tensor([[0.0138, 0.0454, 0.3055, 0.1497],
        [0.4256, 0.0580, 0.7895, 0.4643],
        [0.9961, 0.6216, 0.9892, 0.9280]])

In [10]:
torch.randint(0,10,[3,4])

tensor([[3, 0, 6, 5],
        [1, 9, 0, 2],
        [7, 8, 8, 7]])

### check size

In [11]:
t = torch.tensor([[[1]]])
t

tensor([[[1]]])

In [12]:
t.item() # restrict to scaler

1

In [13]:
t.numpy()

array([[[1]]])

In [14]:
t = torch.Tensor([[[1]]]) # capital T, with type
t.numpy()

array([[[1.]]], dtype=float32)

In [15]:
t.size()

torch.Size([1, 1, 1])

In [18]:
t.size(0), t.size(1), t.size(2)

(1, 1, 1)

### reshape tensor without change the original one

In [28]:
t = torch.Tensor(array1)
t.view([-1]) # -1, depend on other dimensions

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [29]:
t.view([2,-1])

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [30]:
t

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

### check dimension

In [31]:
t.dim()

2

### max, std

In [32]:
t.max()

tensor(11.)

In [33]:
t.std()

tensor(3.6056)

### transpose

In [34]:
t.t()

tensor([[ 0.,  4.,  8.],
        [ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.]])

In [74]:
t3 = torch.Tensor(np.arange(24).reshape(2,3,4))
t3

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [36]:
t3.transpose(0,1) # change the 0th and 1st dim

tensor([[[ 0.,  1.,  2.,  3.],
         [12., 13., 14., 15.]],

        [[ 4.,  5.,  6.,  7.],
         [16., 17., 18., 19.]],

        [[ 8.,  9., 10., 11.],
         [20., 21., 22., 23.]]])

In [37]:
t3.permute(1,0,2)

tensor([[[ 0.,  1.,  2.,  3.],
         [12., 13., 14., 15.]],

        [[ 4.,  5.,  6.,  7.],
         [16., 17., 18., 19.]],

        [[ 8.,  9., 10., 11.],
         [20., 21., 22., 23.]]])

In [38]:
t3.permute(2,1,0)

tensor([[[ 0., 12.],
         [ 4., 16.],
         [ 8., 20.]],

        [[ 1., 13.],
         [ 5., 17.],
         [ 9., 21.]],

        [[ 2., 14.],
         [ 6., 18.],
         [10., 22.]],

        [[ 3., 15.],
         [ 7., 19.],
         [11., 23.]]])

### get value

In [39]:
t3

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [40]:
# get 10
t3[0,2,2]

tensor(10.)

In [41]:
# get 0-11
t3[0]

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [43]:
# get first row
t3[:,0,:]

tensor([[ 0.,  1.,  2.,  3.],
        [12., 13., 14., 15.]])

In [44]:
# get first col
t3[:,:,0]

tensor([[ 0.,  4.,  8.],
        [12., 16., 20.]])

### data type

In [45]:
t3.dtype

torch.float32

In [47]:
torch.ones([3,2], dtype=torch.int).dtype

torch.int32

In [62]:
t4 = torch.Tensor(np.arange(12, dtype=np.int32))
t4.dtype # default change to float32 when create tensor with T

torch.float32

In [63]:
t5 = torch.tensor(np.arange(12, dtype=np.int32))
t5.dtype # keep the original type

torch.int32

In [64]:
t4.int() # change to int type

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.int32)

### calculation

In [75]:
t3

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

In [76]:
t6 = torch.ones([2,3,4])
t3+t6

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])

In [77]:
torch.add(t3, t6)

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])

In [78]:
t3.add_(t6)
t3

tensor([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],

        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]])

### cuda

In [79]:
torch.cuda.is_available() # no GPU, use CPU

False