In [8]:
from torchvision import transforms
import numpy as np

data = np.random.randint(0, 255, size=12)
img = data.reshape(2,2,3)
print(img, img.shape)

[[[ 45 173  11]
  [123 110  62]]

 [[229 202  63]
  [145 167  49]]] (2, 2, 3)


In [9]:
img_tensor = transforms.ToTensor()(img)
print(img_tensor, img_tensor.shape)

tensor([[[ 45, 123],
         [229, 145]],

        [[173, 110],
         [202, 167]],

        [[ 11,  62],
         [ 63,  49]]], dtype=torch.int32) torch.Size([3, 2, 2])


In [16]:
import torch

img_tensor = img_tensor.float()
norm_img = transforms.Normalize((10,10,10), (1,1,1))(img_tensor) # (mean, std) same shape as channel
print(norm_img)

tensor([[[ 35., 113.],
         [219., 135.]],

        [[163., 100.],
         [192., 157.]],

        [[  1.,  52.],
         [ 53.,  39.]]])


In [ ]:
transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean, std)
])